server: chat.freenode.net:+6697
nickname: mybot
channel: "##mychannel"
# how frequently to check hidden services, in seconds
interval: 120
# optional server password
#password: hunter2

# optional SASL PLAIN details
#sasl:
#  username: mybot
#  password: hunter3

services:
  "freenode v2":
    host: freenodeok2gncmy.onion
    port: 6667
    # data to send to the hidden service
    send: "USER u s e r\r\n"
    # what the first line we read from the hidden service should be
    read: ":zettel.freenode.net NOTICE * :*** Looking up your hostname..."

  "freenode v3":
    host: ajnvpgl6prmkb7yktvue6im5wiedlz2w32uhcwaamdiecdrfpwwgnlqd.onion
    port: 6667
    send: "USER u s e r\r\n"
    read: ":zettel.freenode.net NOTICE * :*** Looking up your hostname..."
